create database bai1_022101082
go;
create table KHACHHANG(
MAKH char(4),
HOTEN varchar(40),
DCHI varchar(40),
SODT varchar(20),
NGSINH smalldatetime,
NGDK smalldatetime,
DOANHSO money,
CONSTRAINT KD PRIMARY KEY (MAKH)
)

Select * from KHACHHANG;

go
create table NHANVIEN(
MANV char(4),
HOTEN varchar(40),
SODT varchar(20),
NGVL smalldatetime,
CONSTRAINT NV PRIMARY KEY (MANV)
)
go
create table SANPHAM(
MASP char(4),
TENSP varchar(40),
DVT varchar(20),
NUOCSX varchar(40),
GIA money,
CONSTRAINT SP PRIMARY KEY (MASP)
)
go
create table HOADON(
SOHD int,
NGHD smalldatetime,
MAKH char(4),
MANV char(4),
TRIGIA money,
PRIMARY KEY(SOHD)
)
go

create table CTHD(
SOHD int,
MASP char(4),
SL int,
PRIMARY KEY (SOHD, MASP)
)
go;
---DROP Table CTHD;
ALTER TABLE HOADON ADD CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE HOADON ADD CONSTRAINT FK_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE CTHD ADD CONSTRAINT FK_MASP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE CTHD ADD CONSTRAINT FK_SOHD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD);

